export enum AuditAction {
  REGISTERED = 'REGISTERED',
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  INVITED = 'INVITED',
  INVITE_ACCEPTED = 'INVITE_ACCEPTED',

  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUNDED = 'REFUNDED',

  FORM_DRAFTED = 'FORM_DRAFTED',
  FORM_UPDATED = 'FORM_UPDATED',
  FORM_SUBMITTED = 'FORM_SUBMITTED',

  DOCUMENT_GENERATED = 'DOCUMENT_GENERATED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  UPLOAD_CONFIRMED = 'UPLOAD_CONFIRMED',
  VERSION_CREATED = 'VERSION_CREATED',
  AGREEMENT_VERSION_CREATED = 'AGREEMENT_VERSION_CREATED',
  CHECKED_OUT = 'CHECKED_OUT',
  CHECKED_IN = 'CHECKED_IN',
  DOWNLOADED = 'DOWNLOADED',
  DRAFT_RETURNED = 'DRAFT_RETURNED',

  AGREEMENT_COMPARED = 'AGREEMENT_COMPARED',
  VERSION_COMPARED = 'VERSION_COMPARED',
  CHANGESET_CREATED = 'CHANGESET_CREATED',

  SUBMITTED_FOR_REVIEW = 'SUBMITTED_FOR_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  COUPLE_APPROVAL_REQUESTED = 'COUPLE_APPROVAL_REQUESTED',

  CASE_ARCHIVED = 'CASE_ARCHIVED',
  LAWYERS_ASSIGNED = 'LAWYERS_ASSIGNED',
  PRIORITY_UPDATED = 'PRIORITY_UPDATED',

  NOTE_CREATED = 'NOTE_CREATED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  VERSION_COMMENTED = 'VERSION_COMMENTED',
  TIMELINE_ENTRY_CREATED = 'TIMELINE_ENTRY_CREATED',

  ILA_COMPLETED = 'ILA_COMPLETED',
  SIGNED = 'SIGNED',
  ARCHIVED = 'ARCHIVED',

  EMAIL_SENT = 'EMAIL_SENT',

  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  OTHER = 'OTHER',
}

export enum AuditModule {
  AUTH = 'Auth',
  INVITATION = 'Invitation',
  PAYMENT = 'Payment',
  FORM = 'Form',
  CASE_MANAGER = 'CaseManager',
  AGREEMENT = 'Agreement',
  S3 = 'S3',
  NOTIFICATION = 'Notification',
}